targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/model/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/src/model/*.dart
        options:
          any_map: true
          explicit_to_json: true
          field_rename: snake
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
